version: '3.8'
services:
  nuxtjs-frontend:
    build: 
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
    container_name: nuxtjs-frontend